<template>
  <v-container
    fluid
    tag="section"
  >
    <v-row justify="center">
      <material-card
        class="pa-6"
        min-width="40%"
      >
        <template v-slot:heading>
          <div class="display-2 font-weight-light">
            Login
          </div>

          <div class="subtitle-1 font-weight-light">
            Fill in your username and password
          </div>
        </template>
        <alert
          :errors="errors"
          :success="success"
          success-txt="Successfully logged in!"
        />
        <template v-if="!mfa">
          <v-form
            ref="form"
            method="post"
            class="pt-8"
            @submit.prevent="login"
          >
            <v-container class="py-0">
              <v-row>
                <v-text-field
                  v-model.trim="username"
                  label="Username*"
                  type="text"
                  outlined
                  :rules="[$validator.required]"
                  data-username
                />
              </v-row>
              <v-row>
                <v-text-field
                  v-model="password"
                  label="Password*"
                  type="password"
                  outlined
                  :rules="[$validator.required]"
                  data-password
                />
              </v-row>
              <v-row>
                <v-checkbox
                  v-model="rememberMe"
                  label="Remember me"
                />
              </v-row>
              <v-row>
                <v-btn
                  to="/auth/forgot-password/"
                  text
                  color="blue darken-1"
                  small
                >
                  Forgot Password?
                </v-btn>
              </v-row>
              <v-spacer />
              <v-col
                class="text-right"
              >
                <v-btn
                  color="blue darken-1"
                  text
                  :loading="$store.state.loading.status"
                  @click="reset()"
                >
                  Reset
                </v-btn>
                <v-btn
                  color="info"
                  class="mr-0"
                  type="submit"
                  :loading="$store.state.loading.status"
                >
                  Login
                </v-btn>
              </v-col>
            </v-container>
          </v-form>
          <div class="divider my-5">
            <span>Or use social networks</span>
          </div>
          <v-row align="center" justify="center">
            <v-btn fab x-small color="white" @click="authenticate('github')">
              <v-icon size="34" dark color="black">
                mdi-github
              </v-icon>
            </v-btn>
            <v-btn fab x-small color="white" @click="authenticate('google')">
              <svg width="32px" height="32px" viewBox="0 0 533.5 544.3" xmlns="http://www.w3.org/2000/svg"><path d="M533.5 278.4c0-18.5-1.5-37.1-4.7-55.3H272.1v104.8h147c-6.1 33.8-25.7 63.7-54.4 82.7v68h87.7c51.5-47.4 81.1-117.4 81.1-200.2z" fill="#4285f4" /><path d="M272.1 544.3c73.4 0 135.3-24.1 180.4-65.7l-87.7-68c-24.4 16.6-55.9 26-92.6 26-71 0-131.2-47.9-152.8-112.3H28.9v70.1c46.2 91.9 140.3 149.9 243.2 149.9z" fill="#34a853" /><path d="M119.3 324.3c-11.4-33.8-11.4-70.4 0-104.2V150H28.9c-38.6 76.9-38.6 167.5 0 244.4l90.4-70.1z" fill="#fbbc04" /><path d="M272.1 107.7c38.8-.6 76.3 14 104.4 40.8l77.7-77.7C405 24.6 339.7-.8 272.1 0 169.2 0 75.1 58 28.9 150l90.4 70.1c21.5-64.5 81.8-112.4 152.8-112.4z" fill="#ea4335" /></svg>
            </v-btn>
            <v-btn fab x-small color="white" @click="authenticate('facebook')">
              <v-icon size="34" dark color="#3b5899">
                mdi-facebook
              </v-icon>
            </v-btn>
            <v-btn fab x-small color="white" @click="authenticate('linkedin')">
              <svg width="28px" height="28px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#1b6499"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 16h-2v-6h2v6zm-1-6.891c-.607 0-1.1-.496-1.1-1.109 0-.612.492-1.109 1.1-1.109s1.1.497 1.1 1.109c0 .613-.493 1.109-1.1 1.109zm8 6.891h-1.998v-2.861c0-1.881-2.002-1.722-2.002 0v2.861h-2v-6h2v1.093c.872-1.616 4-1.736 4 1.548v3.359z" /></svg>
            </v-btn>
          </v-row>
        </template>
        <template v-else>
          <v-form
            ref="form"
            method="post"
            class="pt-8"
            @submit.prevent="login"
          >
            <v-container class="py-0">
              <div v-if="mfaType === 'MISSING_AUTHENTICATOR'" class="title">
                Enter the 2-step verification generated by your authenticator app.
              </div>
              <div v-else class="title">
                Enter the SMS code you received on your mobile.
              </div>
              <v-row align="center" justify="center" class="py-4">
                <v-text-field
                  v-model="mfaCode"
                  label="Code*"
                  type="number"
                  class="purple-input shrink"
                  :rules="[$validator.required,$validator.mfa]"
                  maxlength="6"
                />
              </v-row>
              <v-row>
                <v-btn
                  to="/auth/disable-mfa/"
                  text
                  color="blue darken-1"
                  small
                >
                  Unable to submit a one-time code?
                </v-btn>
              </v-row>
              <v-spacer />
              <v-col
                class="text-right"
              >
                <v-btn
                  color="blue darken-1"
                  text
                  :loading="$store.state.loading.status"
                  @click="reset"
                >
                  Cancel
                </v-btn>
                <v-btn
                  color="info"
                  class="mr-0"
                  type="submit"
                  :loading="$store.state.loading.status"
                >
                  Login
                </v-btn>
              </v-col>
            </v-container>
          </v-form>
        </template>
      </material-card>
    </v-row>
  </v-container>
</template>

<script>

import AuthAPI from '@@/api/auth'
import MaterialCard from '@@/components/base/MaterialCard'
import Alert from '@@/components/base/Alert'

export default {
  name: 'Login',
  components: { Alert, MaterialCard },
  layout: 'Home',
  data () {
    return {
      success: false,
      username: '',
      password: '',
      rememberMe: false,
      mfa: false,
      mfaType: null,
      mfaCode: '',
      errors: []
    }
  },
  created () {
    if (this.$store.getters['auth/isAuthenticated']) {
      this.initUser()
        .then(() => {
          this.redirect()
        })
    }
  },
  mounted () {
    this.$store.dispatch('page/title', 'Login')
  },
  methods: {
    goHome (v) {
      if (!v) {
        this.$router.push('/dashboard/home/')
      }
    },
    login () {
      if (!this.$refs.form.validate()) {
        return
      }
      this.$store.dispatch('loading/start')
      this.success = false
      this.errors = []

      const payload = {
        username: this.username,
        password: this.hash(this.password),
        code: this.mfaCode,
        rememberMe: this.rememberMe
      }
      this.$store.dispatch('auth/login', payload)
        .then(() => {
          this.success = true
          this.redirect()
        })
        .catch((err) => {
          const errs = this.parseError(err)
          if (errs[0].status === '422') {
            this.mfa = true
            this.mfaType = errs[0].code
            return
          }
          this.errors = errs
        })
        .finally(() => {
          this.$store.dispatch('loading/finish')
        })
    },
    redirect () {
      const to = this.$route.query.to
      if (typeof to !== 'undefined') {
        this.$router.push({ path: to })
      } else {
        this.$router.push('/dashboard/home/')
      }
    },
    reset () {
      this.success = false
      this.errors = []
      this.username = ''
      this.password = ''
      this.mfa = false
      this.mfaType = null
      this.mfaCode = ''
      this.$refs.form.reset()
    },
    authenticate (provider) {
      this.$store.dispatch('loading/start')
      AuthAPI.socialRedirect(provider)
        .then((r) => {
          location.href = r.data.redirect_uri
        }).catch((err) => {
          this.errors = this.parseError(err)
        })
        .finally(() => {
          this.$store.dispatch('loading/finish')
        })
    }
  }
}
</script>
